from __future__ import annotations

import structlog

# diagnosis_pb2 and diagnosis_pb2_grpc are generated by scripts/gen_proto.sh.
# Run `make proto` before starting the service or running tests.
import diagnosis_pb2  # type: ignore[import]
import diagnosis_pb2_grpc  # type: ignore[import]

from src.events.producer import DiagnosisProducer
from src.grpc.converters import doc_to_grpc_record
from src.models.diagnosis import DiagnosisSubmittedEvent
from src.repositories.diagnosis_repository import DiagnosisRepository

log = structlog.get_logger(__name__)


class DiagnosisServicer(diagnosis_pb2_grpc.DiagnosisServiceServicer):
    def __init__(self, repo: DiagnosisRepository, producer: DiagnosisProducer) -> None:
        self._repo = repo
        self._producer = producer

    async def Diagnose(
        self,
        request: diagnosis_pb2.DiagnoseRequest,
        context: object,
    ) -> diagnosis_pb2.DiagnoseResponse:
        diagnosis_id = await self._repo.create_pending(
            farm_id=request.farm_id,
            farmer_id=request.farmer_id,
            subject_type=request.subject_type,
            subject_name=request.subject_name,
            image_urls=list(request.image_urls),
        )

        event = DiagnosisSubmittedEvent(
            diagnosis_id=diagnosis_id,
            farm_id=request.farm_id,
            farmer_id=request.farmer_id,
            subject_type=request.subject_type,  # type: ignore[arg-type]
            subject_name=request.subject_name,
            image_urls=list(request.image_urls),
            symptoms=request.symptoms or None,
            duration_days=request.duration_days or None,
        )
        # Publish to Kafka — inference runs asynchronously in DiagnosisConsumer
        await self._producer.publish_submitted(event)

        log.info(
            "diagnosis queued",
            diagnosis_id=diagnosis_id,
            farm_id=request.farm_id,
            subject_type=request.subject_type,
        )
        return diagnosis_pb2.DiagnoseResponse(diagnosis_id=diagnosis_id, status="pending")

    async def GetDiagnosis(
        self,
        request: diagnosis_pb2.GetDiagnosisRequest,
        context: object,
    ) -> diagnosis_pb2.DiagnosisRecord:
        doc = await self._repo.find_by_id(request.diagnosis_id)
        if doc is None:
            import grpc
            await context.abort(grpc.StatusCode.NOT_FOUND, "Diagnosis not found")  # type: ignore[union-attr]
        return doc_to_grpc_record(doc)  # type: ignore[arg-type]
