"""
gRPC servicer for DiagnosisService.

Implements DiagnosisService.Diagnose from proto/diagnosis.proto.
Inference runs synchronously in the request handler so the caller receives
the full diagnosis result in a single RPC round-trip.

Kafka async path (kafka_consumer.py) handles the fan-out to
notification-service and farm-service via the diagnosis.completed topic.

Run `make proto` to regenerate diagnosis_pb2.py / diagnosis_pb2_grpc.py
before starting this server.
"""

from __future__ import annotations

import sys as _sys
import time
from datetime import datetime, timezone
from typing import Any

# ── grpcio shadow fix ──────────────────────────────────────────────────────────
# src/grpc/ exists in this project. When src/ is on sys.path (e.g. pytest adds it
# via pyproject.toml pythonpath or conftest.py), `import grpc` resolves to the
# local src/grpc/ package instead of the installed grpcio module.
# This block forces the real grpcio grpc module to load.
def _load_real_grpc() -> object:
    import importlib
    _sys.modules.pop("grpc", None)  # evict any cached local src/grpc/ module
    _saved = list(_sys.path)
    _sys.path[:] = [p for p in _sys.path if not p.endswith(("/src", "\\src"))]
    try:
        return importlib.import_module("grpc")
    finally:
        _sys.path[:] = _saved

import grpc  # noqa: E402
if not hasattr(grpc, "StatusCode"):
    grpc = _load_real_grpc()  # type: ignore[assignment]
del _load_real_grpc
# ── end shadow fix ─────────────────────────────────────────────────────────────

import structlog
from bson import ObjectId

# Generated by scripts/gen_proto.sh — run `make proto` first
import diagnosis_pb2  # type: ignore[import]
import diagnosis_pb2_grpc  # type: ignore[import]

from src.inference_service import run_inference
from src.prescription_service import get_prescriptions
from src.utils.disease_taxonomy import TAXONOMY_BY_CODE

log = structlog.get_logger(__name__)

# Sentinel used when the real EfficientNet model is wired in.
# REPLACE_WITH_EFFICIENTNET: set to actual model version string from TF Serving metadata.
_AI_MODEL_VERSION = "mock-v0"


class DiagnosisServicer(diagnosis_pb2_grpc.DiagnosisServiceServicer):
    """
    gRPC servicer that owns the inference → MongoDB → response pipeline.

    mongo_db: AsyncIOMotorDatabase passed in from main.py / tests.
    kafka_producer: optional DiagnosisProducer; if supplied, publishes
                    diagnosis.completed after every successful inference.
    """

    def __init__(self, mongo_db: Any, kafka_producer: Any = None) -> None:
        self._db = mongo_db
        self._col = mongo_db["diagnoses"]
        self._producer = kafka_producer

    # ------------------------------------------------------------------
    # DiagnosisService.Diagnose
    # ------------------------------------------------------------------

    async def Diagnose(
        self,
        request: diagnosis_pb2.DiagnoseRequest,
        context: grpc.aio.ServicerContext,  # type: ignore[name-defined]
    ) -> diagnosis_pb2.DiagnoseResponse:

        log.info(
            "Diagnose RPC received",
            farm_id=request.farm_id,
            subject_type=request.subject_type,
            subject_name=request.subject_name,
        )

        start_ns = time.monotonic_ns()
        now = datetime.now(timezone.utc)
        oid = ObjectId()
        diagnosis_id = str(oid)

        # ── Step 1: Run inference ──────────────────────────────────────────
        # REPLACE_WITH_EFFICIENTNET: download image bytes from request.image_urls here.
        # e.g.  image_bytes = await _fetch_images(request.image_urls)
        image_bytes: list[bytes] = []   # [MOCK] real: fetched from S3 URLs

        try:
            result = run_inference(
                image_bytes,
                request.subject_type,
                request.subject_name,
            )
        except Exception as exc:
            log.exception("inference failed", diagnosis_id=diagnosis_id)
            await self._col.insert_one(_build_failed_doc(oid, request, now))
            await context.abort(grpc.StatusCode.INTERNAL, f"Inference error: {exc}")

        elapsed_ms = (time.monotonic_ns() - start_ns) // 1_000_000

        # ── Step 2: Fetch prescriptions ───────────────────────────────────
        prescriptions = get_prescriptions(result.disease_code)

        # ── Step 3: Write full document to MongoDB ────────────────────────
        doc = _build_completed_doc(oid, request, result, prescriptions, elapsed_ms, now)
        await self._col.insert_one(doc)

        log.info(
            "diagnosis saved",
            diagnosis_id=diagnosis_id,
            disease_code=result.disease_code,
            confidence=result.confidence,
            elapsed_ms=elapsed_ms,
        )

        # ── Step 4: Publish diagnosis.completed (non-blocking, best-effort) ──
        if self._producer is not None:
            try:
                await self._producer.publish_completed(
                    diagnosis_id=diagnosis_id,
                    farm_id=request.farm_id,
                    farmer_id=request.farmer_id,
                    result=result,  # duck-typed: needs .disease["code"/"name"], .confidence, .severity
                )
            except Exception:
                log.exception("failed to publish diagnosis.completed", diagnosis_id=diagnosis_id)

        # ── Step 5: Build and return response ────────────────────────────
        proto_prescriptions = [
            diagnosis_pb2.PrescriptionProto(
                step_number=p["step_number"],
                action=p["action"],
                product_name=p["product_name"],
                product_type=p["product_type"],
                dosage=p["dosage"],
                frequency=p["frequency"],
            )
            for p in prescriptions
        ]

        return diagnosis_pb2.DiagnoseResponse(
            diagnosis_id=diagnosis_id,
            status="completed",
            disease_name=result.disease_name,
            disease_code=result.disease_code,
            confidence=result.confidence,
            severity=result.severity,
            description=result.description,
            prescriptions=proto_prescriptions,
            processing_time_ms=elapsed_ms,
            ai_model_version=_AI_MODEL_VERSION,
        )

    # ------------------------------------------------------------------
    # DiagnosisService.GetDiagnosis
    # ------------------------------------------------------------------

    async def GetDiagnosis(
        self,
        request: diagnosis_pb2.GetDiagnosisRequest,
        context: grpc.aio.ServicerContext,  # type: ignore[name-defined]
    ) -> diagnosis_pb2.DiagnosisRecord:

        try:
            oid = ObjectId(request.diagnosis_id)
        except Exception:
            await context.abort(grpc.StatusCode.INVALID_ARGUMENT, "Invalid diagnosis_id format")

        doc = await self._col.find_one({"_id": oid})
        if doc is None:
            await context.abort(grpc.StatusCode.NOT_FOUND, "Diagnosis not found")

        diag = doc.get("diagnosis") or {}
        record = diagnosis_pb2.DiagnosisRecord(
            id=str(doc["_id"]),
            status=doc["status"],
            farm_id=doc["farm_id"],
            farmer_id=doc["farmer_id"],
            subject_type=doc["subject_type"],
            subject_name=doc["subject_name"],
            disease_name=diag.get("disease_name", ""),
            disease_code=diag.get("disease_code", ""),
            confidence=diag.get("confidence", 0.0),
            severity=diag.get("severity", ""),
            description=diag.get("description", ""),
            processing_time_ms=doc.get("processing_time_ms") or 0,
            ai_model_version=doc.get("ai_model_version", ""),
            created_at=doc["created_at"].isoformat(),
        )
        for p in doc.get("prescriptions", []):
            record.prescriptions.append(
                diagnosis_pb2.PrescriptionProto(
                    step_number=p.get("step_number", p.get("step", 0)),
                    action=p.get("action", ""),
                    product_name=p.get("product_name", ""),
                    product_type=p.get("product_type", ""),
                    dosage=p.get("dosage", ""),
                    frequency=p.get("frequency", ""),
                )
            )
        return record


# ------------------------------------------------------------------
# Document builders (schemas.md exact match)
# ------------------------------------------------------------------

def _build_completed_doc(
    oid: ObjectId,
    request: Any,
    result: Any,
    prescriptions: list[dict],
    elapsed_ms: int,
    now: datetime,
) -> dict[str, Any]:
    """Build the full MongoDB document as defined in docs/schemas.md."""
    return {
        "_id": oid,
        "farm_id": request.farm_id,
        "farmer_id": request.farmer_id,
        "subject_type": request.subject_type,
        "subject_name": request.subject_name,
        "image_urls": list(request.image_urls),
        "ai_model_version": _AI_MODEL_VERSION,
        "diagnosis": {
            "disease_name": result.disease_name,
            "disease_code": result.disease_code,
            "confidence": result.confidence,
            "severity": result.severity,
            "description": result.description,
            "affected_area": None,
        },
        "alternative_diagnoses": [],
        "prescriptions": prescriptions,
        "farmer_feedback": None,
        "status": "completed",
        "processing_time_ms": elapsed_ms,
        "created_at": now,
        "updated_at": now,
    }


def _build_failed_doc(
    oid: ObjectId,
    request: Any,
    now: datetime,
) -> dict[str, Any]:
    return {
        "_id": oid,
        "farm_id": request.farm_id,
        "farmer_id": request.farmer_id,
        "subject_type": request.subject_type,
        "subject_name": request.subject_name,
        "image_urls": list(request.image_urls),
        "ai_model_version": _AI_MODEL_VERSION,
        "diagnosis": None,
        "alternative_diagnoses": [],
        "prescriptions": [],
        "farmer_feedback": None,
        "status": "failed",
        "processing_time_ms": None,
        "created_at": now,
        "updated_at": now,
    }


# ------------------------------------------------------------------
# Server bootstrap (used by main.py)
# ------------------------------------------------------------------

def create_server(mongo_db: Any, kafka_producer: Any = None) -> grpc.aio.Server:  # type: ignore[name-defined]
    server = grpc.aio.server()
    diagnosis_pb2_grpc.add_DiagnosisServiceServicer_to_server(
        DiagnosisServicer(mongo_db, kafka_producer), server
    )
    return server
