from __future__ import annotations

import sys as _sys

# ── grpcio shadow fix ──────────────────────────────────────────────────────────
# src/grpc/ exists in this project. With PYTHONPATH=/app/src, `import grpc`
# resolves to the local src/grpc/ module instead of the grpcio package.
# Pre-load the real grpcio into sys.modules so all subsequent imports use it.
def _preload_real_grpc() -> None:
    import importlib
    _saved = list(_sys.path)
    _sys.path[:] = [p for p in _sys.path if not p.endswith(("/src", "\\src"))]
    try:
        real_grpc = importlib.import_module("grpc")
        _sys.modules["grpc"] = real_grpc
    finally:
        _sys.path[:] = _saved

_preload_real_grpc()
del _preload_real_grpc
# ── end shadow fix ─────────────────────────────────────────────────────────────

import asyncio
import logging
from contextlib import asynccontextmanager
from typing import AsyncIterator

import grpc
import structlog
import uvicorn
from fastapi import FastAPI
from motor.motor_asyncio import AsyncIOMotorClient

from src.config import settings
from src.events.consumer import DiagnosisConsumer
from src.events.producer import DiagnosisProducer

# diagnosis_pb2_grpc generated by scripts/gen_proto.sh — run `make proto` first
import diagnosis_pb2_grpc  # type: ignore[import]

from src.grpc.server import DiagnosisServicer
from src.repositories.diagnosis_repository import DiagnosisRepository
from src.rest.router import router, set_repository, set_producer

structlog.configure(
    wrapper_class=structlog.make_filtering_bound_logger(
        getattr(logging, settings.LOG_LEVEL.upper(), logging.INFO)
    ),
)

log = structlog.get_logger(__name__)

# Module-level gRPC server so the lifespan function can manage it
_grpc_server: grpc.aio.Server | None = None


@asynccontextmanager
async def lifespan(app: FastAPI) -> AsyncIterator[None]:
    global _grpc_server

    mongo_client: AsyncIOMotorClient = AsyncIOMotorClient(settings.MONGODB_URI)  # type: ignore[type-arg]
    db = mongo_client[settings.MONGO_DB]
    repo = DiagnosisRepository(db)
    producer = DiagnosisProducer()
    consumer = DiagnosisConsumer(repo, producer)

    set_repository(repo)
    set_producer(producer)

    await producer.start()
    await consumer.start()

    _grpc_server = grpc.aio.server()
    diagnosis_pb2_grpc.add_DiagnosisServiceServicer_to_server(
        DiagnosisServicer(repo, producer), _grpc_server
    )
    _grpc_server.add_insecure_port(f"[::]:{settings.GRPC_PORT}")
    await _grpc_server.start()
    log.info("gRPC server started", port=settings.GRPC_PORT)

    yield  # ── running ────────────────────────────────────────────────────────

    log.info("shutting down")
    await consumer.stop()
    await producer.stop()
    await _grpc_server.stop(grace=5)
    mongo_client.close()


app = FastAPI(title="diagnosis-service", version="0.1.0", lifespan=lifespan)
app.include_router(router, prefix="/api/v1")


if __name__ == "__main__":
    uvicorn.run(
        "src.main:app",
        host="0.0.0.0",
        port=settings.REST_PORT,
        log_level=settings.LOG_LEVEL,
    )
